#!/bin/bash
## test-setup
## =stub=
## version 0.0.0 - stub
exit 0
##################################################
test-setup() {
 true
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-setup
##################################################
## generated by create-stub2.sh v0.1.1
## on Fri, 27 Apr 2018 13:56:39 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
